---
name: concourse

# Meta property overrides
meta:
  environment: ~
  atc:
    external_url: ~
  riemann_emitter:
    host: ~
    port: 5555
  rds:
    region: ~

# replace with bosh status --uuid
director_uuid: ~

releases:
- {name: concourse, version: latest}
- {name: garden-runc, version: latest}
- {name: riemann, version: latest}

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: web
  instances: 1
  stemcell: default
  jobs:
  - name: atc
    release: concourse
    properties:
      web_bind_port: 8080
      external_url: (( grab meta.atc.external_url ))
  - name: tsa
    release: concourse
  - name: riemann-emitter
    release: riemann
    properties:
      riemann_emitter:
        host: (( grab meta.riemann_emitter.host ))
        port: (( grab meta.riemann_emitter.port ))
        health: true

- name: worker
  instances: 1
  stemcell: default
  jobs:
  - name: groundcrew
    release: concourse
    properties:
      additional_resource_types:
      - type: slack-notification
        image: docker:///cfcommunity/slack-notification-resource
      - type: cg-common
        image: docker:///18fgsa/cg-common-resource
      - type: 18f-bosh-deployment
        image: docker:///18fgsa/bosh-deployment-resource
      drain_timeout: 15m
  - name: baggageclaim
    release: concourse
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        enable_graph_cleanup: true
        default_container_grace_time: 10m
        max_containers: 250
        network_pool: 10.254.0.0/20
  - name: riemann-emitter
    release: riemann
    properties:
      riemann_emitter:
        host: (( grab meta.riemann_emitter.host ))
        port: (( grab meta.riemann_emitter.port ))
        health: true

- name: iaas-worker
  stemcell: default
  instances: 0
  jobs:
  - name: groundcrew
    release: concourse
    properties:
      additional_resource_types:
      - type: slack-notification
        image: docker:///cfcommunity/slack-notification-resource
      - type: cg-common
        image: docker:///18fgsa/cg-common-resource
      - type: 18f-bosh-deployment
        image: docker:///18fgsa/bosh-deployment-resource
      drain_timeout: 15m
      team: main
      tags:
      - iaas
  - (( grab instance_groups.worker.jobs.baggageclaim ))
  - (( grab instance_groups.worker.jobs.garden ))
  - (( grab instance_groups.worker.jobs.riemann-emitter ))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
