---
name: concourse

releases:
- {name: concourse, version: latest}
- {name: garden-runc, version: latest}

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: web
  instances: 1
  stemcell: default
  jobs:
  - name: atc
    release: concourse
    properties:
      prometheus:
        bind_ip: 0.0.0.0
        bind_port: 9110
      web_bind_port: 8080
      intercept_idle_timeout: 10m
      external_url: (( param "specify external url" ))
  - name: tsa
    release: concourse

- name: worker
  instances: 1
  stemcell: default
  jobs:
  - name: groundcrew
    release: concourse
    properties:
      additional_resource_types:
      - type: slack-notification
        image: docker:///cfcommunity/slack-notification-resource
      - type: cg-common
        image: docker:///18fgsa/cg-common-resource
      - type: 18f-bosh-deployment
        image: docker:///18fgsa/bosh-deployment-resource
      drain_timeout: 15m
    consumes: {baggageclaim: {from: default-baggageclaim}}
  - name: baggageclaim
    release: concourse
    provides: {baggageclaim: {as: default-baggageclaim}}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        graph_cleanup_threshold_in_mb: 2048

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
