---
jobs:
- name: deploy-concourse-staging
  serial: true
  plan:
  - aggregate:
    - get: pipeline-tasks
      trigger: false
    - get: concourse-config
      trigger: true
    - get: common-staging
      trigger: true
    - get: concourse-stemcell
      trigger: false
    - get: concourse-release
      trigger: true
    - get: garden-runc-release
      trigger: false
  - task: concourse-manifest
    file: pipeline-tasks/spiff-merge.yml
    config:
      inputs:
        - name: pipeline-tasks
        - name: concourse-config
        - name: common-staging
      params:
        OUTPUT_FILE: spiff-merge/manifest.yml
        SOURCE_FILE: concourse-config/concourse.yml
        MERGE_FILES: common-staging/secrets.yml
  - put: concourse-staging-deployment
    params:
      cert: common-staging/boshCA.crt
      manifest: spiff-merge/manifest.yml
      releases:
        - concourse-release/*.tgz
        - garden-runc-release/*.tgz
      stemcells:
        - concourse-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy Concourse on staging
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed Concourse on staging
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

- name: deploy-concourse-production
  serial: true
  plan:
  - aggregate:
    - get: pipeline-tasks
      trigger: false
    - get: concourse-config
      trigger: true
      passed: [deploy-concourse-staging]
    - get: common-production
      trigger: true
    - get: concourse-stemcell
      trigger: false
      passed: [deploy-concourse-staging]
    - get: concourse-release
      trigger: true
      passed: [deploy-concourse-staging]
    - get: garden-runc-release
      trigger: false
      passed: [deploy-concourse-staging]
  - task: concourse-manifest
    file: pipeline-tasks/spiff-merge.yml
    config:
      inputs:
        - name: pipeline-tasks
        - name: concourse-config
        - name: common-production
      params:
        OUTPUT_FILE: spiff-merge/manifest.yml
        SOURCE_FILE: concourse-config/concourse.yml
        MERGE_FILES: common-production/secrets.yml
  - put: concourse-production-deployment
    params:
      cert: common-production/boshCA.crt
      manifest: spiff-merge/manifest.yml
      releases:
        - concourse-release/*.tgz
        - garden-runc-release/*.tgz
      stemcells:
        - concourse-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy Concourse on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed Concourse on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: concourse-config
  type: git
  source:
    uri: {{concourse-config-git-url}}
    branch: {{concourse-config-git-branch}}
    paths:
    - concourse.yml

- name: common-production
  type: cg-common
  source:
    bucket_name: {{concourse-production-private-bucket}}
    region: {{aws-region}}
    access_key_id: {{ci-access-key-id}}
    secret_access_key: {{ci-secret-access-key}}
    secrets_file: concourse-tooling-prod.yml
    secrets_passphrase: {{concourse-production-private-passphrase}}
    bosh_cert: bosh-tooling.pem

- name: common-staging
  type: cg-common
  source:
    bucket_name: {{concourse-staging-private-bucket}}
    region: {{aws-region}}
    access_key_id: {{ci-access-key-id}}
    secret_access_key: {{ci-secret-access-key}}
    secrets_file: concourse-tooling-staging.yml
    secrets_passphrase: {{concourse-staging-private-passphrase}}
    bosh_cert: bosh-tooling.pem

#- name: concourse-stemcell
#  type: bosh-io-stemcell
#  source:
#    name: {{concourse-stemcell}}

- name: concourse-stemcell
  type: s3
  source:
     bucket: cg-stemcell-images
     region_name: {{aws-region}}
     access_key_id: {{ci-access-key-id}}
     secret_access_key: {{ci-secret-access-key}}
     regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz

- name: concourse-release
  type: bosh-io-release
  source:
    repository: concourse/concourse

- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-runc-release

- name: concourse-production-deployment
  type: 18f-bosh-deployment
  source:
    target: {{concourse-production-deployment-bosh-target}}
    username: {{concourse-production-deployment-bosh-username}}
    password: {{concourse-production-deployment-bosh-password}}
    deployment: {{concourse-production-deployment-bosh-deployment}}

- name: concourse-staging-deployment
  type: 18f-bosh-deployment
  source:
    target: {{concourse-staging-deployment-bosh-target}}
    username: {{concourse-staging-deployment-bosh-username}}
    password: {{concourse-staging-deployment-bosh-password}}
    deployment: {{concourse-staging-deployment-bosh-deployment}}

- name: slack
  type: slack-notification-docker
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: slack-notification-docker
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: 18f-bosh-deployment
  type: docker-image
  source:
    repository: 18fgsa/bosh-deployment-resource
- name: cg-common
  type: docker-image
  source:
    repository: 18fgsa/cg-common-resource
