---
jobs:
- name: container-bosh-development
  plan:
  - aggregate:
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: development
      BOSH_ENVIRONMENT: {{development-bosh-target}}
      BOSH_USERNAME: {{development-bosh-username}}
      BOSH_PASSWORD: {{development-bosh-password}}
      BOSH_CACERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "6" # cyan

- name: container-bosh-staging
  plan:
  - aggregate:
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: staging
      BOSH_ENVIRONMENT: {{staging-bosh-target}}
      BOSH_USERNAME: {{staging-bosh-username}}
      BOSH_PASSWORD: {{staging-bosh-password}}
      BOSH_CACERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "2" # green

- name: container-bosh-production
  plan:
  - aggregate:
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: PRODUCTION
      BOSH_ENVIRONMENT: {{production-bosh-target}}
      BOSH_USERNAME: {{production-bosh-username}}
      BOSH_PASSWORD: {{production-bosh-password}}
      BOSH_CACERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "1" # red

- name: container-bosh-tooling
  plan:
  - aggregate:
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: Tooling
      BOSH_ENVIRONMENT: {{tooling-bosh-target}}
      BOSH_CLIENT: {{tooling-bosh-uaa-client}}
      BOSH_CLIENT_SECRET: {{tooling-bosh-uaa-client-secret}}
      BOSH_CACERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "3" # yellow

resources:
- name: concourse-config
  type: git
  source:
    uri: {{concourse-config-git-url}}
    branch: {{concourse-config-git-branch}}
    paths:
    - jumpbox.yml
    - jumpbox.sh

- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: {{production-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: master-bosh.crt

resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
