---
jobs:
- name: container-bosh-development
  plan:
  - aggregate: &resources
    - get: cg-scripts
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: development
      BOSH_ENVIRONMENT: {{development-bosh-target}}
      BOSH_CLIENT: {{development-bosh-client}}
      BOSH_CLIENT_SECRET: {{development-bosh-client-secret}}
      BOSH_CA_CERT: master-bosh-root-cert/master-bosh.crt
      CREDHUB_CA_CERT: master-bosh-root-cert/master-bosh.crt
      CREDHUB_CLIENT: ((developmentbosh/credhub-admin-client))
      CREDHUB_SECRET: ((developmentbosh/credhub-admin-secret))
      CREDHUB_SERVER: ((developmentbosh/credhub-api-server))
      PROMPT_COLOR: "6" # cyan

- name: container-bosh-staging
  plan:
  - aggregate: *resources
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: staging
      BOSH_ENVIRONMENT: {{staging-bosh-target}}
      BOSH_CLIENT: {{staging-bosh-client}}
      BOSH_CLIENT_SECRET: {{staging-bosh-client-secret}}
      BOSH_CA_CERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "2" # green

- name: container-bosh-production
  plan:
  - aggregate: *resources
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: PRODUCTION
      BOSH_ENVIRONMENT: {{production-bosh-target}}
      BOSH_CLIENT: {{production-bosh-client}}
      BOSH_CLIENT_SECRET: {{production-bosh-client-secret}}
      BOSH_CA_CERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "1" # red

- name: container-bosh-tooling
  plan:
  - aggregate: *resources
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: Tooling
      BOSH_ENVIRONMENT: {{tooling-bosh-target}}
      BOSH_CLIENT: {{tooling-bosh-uaa-client}}
      BOSH_CLIENT_SECRET: {{tooling-bosh-uaa-client-secret}}
      BOSH_CA_CERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "3" # yellow

- name: container-bosh-master
  plan:
  - aggregate: *resources
  - task: jumpbox
    file: concourse-config/jumpbox.yml
    params:
      BOSH_DIRECTOR_NAME: Master
      BOSH_ENVIRONMENT: {{master-bosh-target}}
      BOSH_CLIENT: {{master-bosh-client}}
      BOSH_CLIENT_SECRET: {{master-bosh-client-secret}}
      BOSH_CA_CERT: master-bosh-root-cert/master-bosh.crt
      PROMPT_COLOR: "5" # magenta

resources:
- name: concourse-config
  type: git
  source:
    uri: {{concourse-config-git-url}}
    branch: {{concourse-config-git-branch}}
    paths:
    - jumpbox.yml
    - jumpbox.sh

- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: {{production-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: master-bosh.crt

- name: cg-scripts
  type: git
  source:
    uri: https://github.com/18F/cg-scripts
    branch: master

resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
