deployment_name: concourse-production
external_url: https://ci.fr.cloud.gov
azs: [z1]
web_vm_type: production-concourse-web
worker_vm_type: production-concourse-worker
iaas_worker_vm_type: production-concourse-iaas-worker
web_vm_extensions: [production-concourse-lb]
worker_vm_extensions: [production-concourse-profile]
iaas_worker_vm_extensions: [production-concourse-iaas-profile]
network_name: production-concourse
web_instances: 3
worker_instances: 7
iaas_worker_instances: 2
build_logs_default: 25
build_logs_maximum: 0
